### ISSUE TITLE
Rename package carbonplan_tonyear -> tonyear

### ISSUE THREAD

**Issue by jhamman** [carbonplan/ton-year#8]
After discussing with @freyac and @badgley, consensous is that the main package here can be renamed to `tonyear`. Steps to be done:

- [x] `git mv carbonplan_tonyear tonyear`
- [x] update `setup.py`
- [x] update imports in Jupyter Notebooks and `tests/test_tonyear.py`

**Comment by freyac** [comment]
See #10!
